public withsharing class calculator{
    public void add(integer a, integer b){
        return a+b;
    }

    public void Sub(integer a, integer b){
        return a-b;
    }
    public void div(integer a, integer b){
        return a/b;
    }
    public void mul(integer a, integer b){
        return a*b;
    }
     public void ihi(integer a, integer b){
        return a*b;
    }
    public void idssfsdhi(integer a, integer b){
        return a*b;
    }
    
}